// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxCSOeEfspHiE_WN-JWqlZB_Dtoe_G5iE',
    appId: '1:247337869230:android:dd1e79489cc84ed7b3f23f',
    messagingSenderId: '247337869230',
    projectId: 'runtimer-b1688',
    storageBucket: 'runtimer-b1688.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvSXJ7tj77rrydasLafqeDN7UCjcc9LpQ',
    appId: '1:247337869230:ios:1ec1ebec3ca1c0eeb3f23f',
    messagingSenderId: '247337869230',
    projectId: 'runtimer-b1688',
    storageBucket: 'runtimer-b1688.firebasestorage.app',
    iosClientId: '247337869230-na6ojg9pj8sgp2ee512b53qu04e6ge4i.apps.googleusercontent.com',
    iosBundleId: 'com.example.runtimerApp',
  );
}
